# Generated by Django 5.2 on 2026-06-06 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteInmobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('presupuesto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(default='Quito', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia_profesional', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(default='General', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_inmueble', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Terreno', 'Terreno'), ('Oficina', 'Oficina')], default='Departamento', max_length=20)),
                ('estado_negocio', models.CharField(choices=[('Disponible', 'Disponible'), ('Arrendado', 'Arrendado'), ('Vendido', 'Vendido')], default='Disponible', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion', models.CharField(max_length=250)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('area_metros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='mi_app.agente')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='mi_app.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Compraventa', 'Compraventa'), ('Arrendamiento', 'Arrendamiento')], max_length=20)),
                ('monto_total_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_firma', models.DateField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='mi_app.clienteinmobiliario')),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='mi_app.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=15)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mi_app.agente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mi_app.clienteinmobiliario')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mi_app.propiedad')),
            ],
        ),
    ]
